name: pack-optimizer
region: nyc

databases:
  - name: pack-optimizer-db
    engine: PG
    version: "16"
    production: false
    cluster_name: pack-optimizer-db-cluster

  - name: pack-optimizer-redis
    engine: REDIS
    version: "7"
    production: false

services:
  - name: pack-optimizer-api
    source_dir: backend
    github:
      repo: YOUR_GITHUB_USERNAME/YOUR_REPO_NAME
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    health_check:
      http_path: /api/v1/healthz
    envs:
      - key: HTTP_PORT
        value: "8080"
      - key: ENVIRONMENT
        value: "production"
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${pack-optimizer-db.DATABASE_URL}
      - key: REDIS_ADDR
        scope: RUN_TIME
        value: ${pack-optimizer-redis.REDIS_HOSTNAME}:${pack-optimizer-redis.REDIS_PORT}
      - key: REDIS_PASSWORD
        scope: RUN_TIME
        value: ${pack-optimizer-redis.REDIS_PASSWORD}
      - key: CORS_ORIGIN
        scope: RUN_TIME
        value: ${pack-optimizer-frontend.PUBLIC_URL}
      - key: RATE_LIMIT_ENABLED
        value: "true"
      - key: RATE_LIMIT_RPM
        value: "100"
      - key: RATE_LIMIT_BURST
        value: "20"
      - key: DDOS_PROTECTION_ENABLED
        value: "true"
      - key: MAX_REQUEST_SIZE
        value: "10485760"
      - key: MAX_HEADER_SIZE
        value: "8192"

  - name: pack-optimizer-frontend
    source_dir: frontend
    github:
      repo: YOUR_GITHUB_USERNAME/YOUR_REPO_NAME
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile
    http_port: 80
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: VITE_API_URL
        scope: BUILD_TIME
        value: ${pack-optimizer-api.PUBLIC_URL}/api/v1

